"""Domain models for culvert barrels, groups, crossings, and materials."""

from .barrel import CulvertBarrel
from .crossing import CulvertCrossing
from .enums import (
    ApplicabilityNoticeCode,
    ControlType,
    CspCorrugation,
    ExitLossSelectionBasis,
    GeometryShape,
    HydraulicResultStatus,
    InletEquationForm,
    ProfileCurve,
    RoughnessSelectionBasis,
)
from .group import CulvertGroup
from .materials import (
    CONCRETE,
    CONCRETE_BOX,
    CONCRETE_PIPE,
    CORRUGATED_STEEL,
    MRWA_CONCRETE_REFERENCE,
    MRWA_CSP_MANNING_TABLE,
    MRWA_CSP_REFERENCE,
    MRWA_PART5B_REFERENCE,
    MRWA_SPEC404_REFERENCE,
    SMOOTH_HDPE,
    CspManningEntry,
    CulvertMaterial,
    ManningRoughnessSelection,
    RoughnessApplicabilityNotice,
    resolve_csp_manning_roughness,
    resolve_manning_roughness,
)
from .results import (
    NCHRP_734_REPRESENTATIVE_BARREL,
    REPRESENTATIVE_BARREL_EQUAL_FLOW_NOTICE,
    BarrelHydraulicResult,
    CrossingHydraulicResult,
    FlowRegime,
    GroupHydraulicResult,
    HydraulicApplicabilityNotice,
)
from .roadway import (
    EPA_SWMM_ROADWAY_SUBMERGENCE_DIGITISATION,
    FHWA_BRIDGE_WATERWAYS_ROADWAY_SUBMERGENCE,
    FHWA_HDS5_ROADWAY_OVERTOPPING,
    FHWA_HY8_ROADWAY_PROFILE_INTEGRATION,
    RoadwayCrestPoint,
    RoadwayCrestProfile,
    RoadwayOvertoppingInput,
    RoadwayProfileWeir,
    RoadwaySurface,
    RoadwayWeir,
)
from .tailwater import (
    FHWA_HDS5_NORMAL_DEPTH_TAILWATER,
    ManningChannelTailwater,
    TailwaterBoundary,
    TailwaterCondition,
    TailwaterInterpolation,
    TailwaterMethod,
    TailwaterRatingCurve,
    TailwaterRatingPoint,
    TailwaterResolution,
    resolve_tailwater,
)

__all__: list[str] = [
    "CONCRETE",
    "CONCRETE_BOX",
    "CONCRETE_PIPE",
    "CORRUGATED_STEEL",
    "EPA_SWMM_ROADWAY_SUBMERGENCE_DIGITISATION",
    "FHWA_BRIDGE_WATERWAYS_ROADWAY_SUBMERGENCE",
    "FHWA_HDS5_NORMAL_DEPTH_TAILWATER",
    "FHWA_HDS5_ROADWAY_OVERTOPPING",
    "FHWA_HY8_ROADWAY_PROFILE_INTEGRATION",
    "MRWA_CONCRETE_REFERENCE",
    "MRWA_CSP_MANNING_TABLE",
    "MRWA_CSP_REFERENCE",
    "MRWA_PART5B_REFERENCE",
    "MRWA_SPEC404_REFERENCE",
    "NCHRP_734_REPRESENTATIVE_BARREL",
    "REPRESENTATIVE_BARREL_EQUAL_FLOW_NOTICE",
    "SMOOTH_HDPE",
    "ApplicabilityNoticeCode",
    "BarrelHydraulicResult",
    "ControlType",
    "CrossingHydraulicResult",
    "CspCorrugation",
    "CspManningEntry",
    "CulvertBarrel",
    "CulvertCrossing",
    "CulvertGroup",
    "CulvertMaterial",
    "ExitLossSelectionBasis",
    "FlowRegime",
    "GeometryShape",
    "GroupHydraulicResult",
    "HydraulicApplicabilityNotice",
    "HydraulicResultStatus",
    "InletEquationForm",
    "ManningChannelTailwater",
    "ManningRoughnessSelection",
    "ProfileCurve",
    "RoadwayCrestPoint",
    "RoadwayCrestProfile",
    "RoadwayOvertoppingInput",
    "RoadwayProfileWeir",
    "RoadwaySurface",
    "RoadwayWeir",
    "RoughnessApplicabilityNotice",
    "RoughnessSelectionBasis",
    "TailwaterBoundary",
    "TailwaterCondition",
    "TailwaterInterpolation",
    "TailwaterMethod",
    "TailwaterRatingCurve",
    "TailwaterRatingPoint",
    "TailwaterResolution",
    "resolve_csp_manning_roughness",
    "resolve_manning_roughness",
    "resolve_tailwater",
]
