"""Inlet-control hydraulics, empirical coefficients, and FHWA equation solvers."""

from .coefficients import (
    BOX_CONCRETE_BEVEL_45_HEADWALL,
    BOX_CONCRETE_CHAMFER_90_HEADWALL,
    BOX_CONCRETE_FLARED_WINGWALLS_30_75,
    BOX_CONCRETE_PARALLEL_WINGWALLS_0,
    CIRCULAR_CMP_HEADWALL,
    CIRCULAR_CMP_MITERED,
    CIRCULAR_CMP_PROJECTING,
    CIRCULAR_CONCRETE_GROOVE_END,
    CIRCULAR_CONCRETE_SQUARE_EDGE,
    STANDARD_INLET_COEFFICIENTS,
    InletCoefficients,
)
from .fhwa import (
    flow_parameter,
    submerged_headwater,
    transition_headwater,
    unsubmerged_headwater_form_1,
    unsubmerged_headwater_form_2,
)
from .modern_box import (
    FHWA_HRT_06_138_REFERENCE,
    FHWA_MODERN_BOX_HW_D_MAX,
    FHWA_MODERN_BOX_HW_D_MIN,
    BoxCrownTreatment,
    BoxWingwallTreatment,
    ModernBoxInlet,
    ModernBoxInletCoefficients,
    ModernBoxInletResult,
    calculate_modern_box_inlet_headwater,
    resolve_modern_box_inlet_coefficients,
)
from .solver import (
    EXTREME_HEADWATER_RATIO,
    HDS5_LABORATORY_HW_D_MAX,
    InletControlResult,
    calculate_inlet_control_headwater,
)

__all__: list[str] = [
    "BOX_CONCRETE_BEVEL_45_HEADWALL",
    "BOX_CONCRETE_CHAMFER_90_HEADWALL",
    "BOX_CONCRETE_FLARED_WINGWALLS_30_75",
    "BOX_CONCRETE_PARALLEL_WINGWALLS_0",
    "CIRCULAR_CMP_HEADWALL",
    "CIRCULAR_CMP_MITERED",
    "CIRCULAR_CMP_PROJECTING",
    "CIRCULAR_CONCRETE_GROOVE_END",
    "CIRCULAR_CONCRETE_SQUARE_EDGE",
    "BoxCrownTreatment",
    "BoxWingwallTreatment",
    "FHWA_HRT_06_138_REFERENCE",
    "FHWA_MODERN_BOX_HW_D_MAX",
    "FHWA_MODERN_BOX_HW_D_MIN",
    "STANDARD_INLET_COEFFICIENTS",
    "InletCoefficients",
    "InletControlResult",
    "ModernBoxInlet",
    "ModernBoxInletCoefficients",
    "ModernBoxInletResult",
    "EXTREME_HEADWATER_RATIO",
    "HDS5_LABORATORY_HW_D_MAX",
    "calculate_inlet_control_headwater",
    "calculate_modern_box_inlet_headwater",
    "flow_parameter",
    "resolve_modern_box_inlet_coefficients",
    "submerged_headwater",
    "transition_headwater",
    "unsubmerged_headwater_form_1",
    "unsubmerged_headwater_form_2",
]
