"""Outlet control hydraulic models and solvers."""

from .full_flow import (
    FullFlowOutletResult,
    calculate_downstream_full_flow_length,
    calculate_full_flow_outlet_headwater,
)
from .losses import (
    BOX_CONCRETE_FLARED_WINGWALLS_30_75,
    BOX_CONCRETE_FLARED_WINGWALLS_ROUNDED,
    BOX_CONCRETE_HEADWALL_ROUNDED,
    BOX_CONCRETE_HEADWALL_SQUARE,
    BOX_CONCRETE_PARALLEL_WINGWALLS_0,
    BOX_CONCRETE_WINGWALLS_10_25,
    PIPE_CMP_BEVELED,
    PIPE_CMP_END_SECTION,
    PIPE_CMP_HEADWALL,
    PIPE_CMP_MITERED,
    PIPE_CMP_PROJECTING,
    PIPE_CONCRETE_BEVELED,
    PIPE_CONCRETE_MITERED,
    PIPE_CONCRETE_PROJECTING_SOCKET,
    PIPE_CONCRETE_PROJECTING_SQUARE,
    PIPE_CONCRETE_ROUNDED,
    PIPE_CONCRETE_SOCKET_END,
    PIPE_CONCRETE_SQUARE_EDGE,
    STANDARD_EXIT_LOSS_COEFFICIENT,
    EntranceLossCoefficient,
    calculate_entrance_loss,
    calculate_exit_loss,
    calculate_friction_loss,
    calculate_total_head_loss,
)
from .partial_flow import (
    PartialFlowOutletResult,
    calculate_partial_flow_outlet_headwater,
)

__all__ = [
    "BOX_CONCRETE_FLARED_WINGWALLS_30_75",
    "BOX_CONCRETE_FLARED_WINGWALLS_ROUNDED",
    "BOX_CONCRETE_HEADWALL_ROUNDED",
    "BOX_CONCRETE_HEADWALL_SQUARE",
    "BOX_CONCRETE_PARALLEL_WINGWALLS_0",
    "BOX_CONCRETE_WINGWALLS_10_25",
    "EntranceLossCoefficient",
    "FullFlowOutletResult",
    "PartialFlowOutletResult",
    "PIPE_CMP_BEVELED",
    "PIPE_CMP_END_SECTION",
    "PIPE_CMP_HEADWALL",
    "PIPE_CMP_MITERED",
    "PIPE_CMP_PROJECTING",
    "PIPE_CONCRETE_BEVELED",
    "PIPE_CONCRETE_MITERED",
    "PIPE_CONCRETE_PROJECTING_SOCKET",
    "PIPE_CONCRETE_PROJECTING_SQUARE",
    "PIPE_CONCRETE_ROUNDED",
    "PIPE_CONCRETE_SOCKET_END",
    "PIPE_CONCRETE_SQUARE_EDGE",
    "STANDARD_EXIT_LOSS_COEFFICIENT",
    "calculate_entrance_loss",
    "calculate_exit_loss",
    "calculate_friction_loss",
    "calculate_full_flow_outlet_headwater",
    "calculate_downstream_full_flow_length",
    "calculate_partial_flow_outlet_headwater",
    "calculate_total_head_loss",
]
